# Generated by Django 5.2.4 on 2025-07-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('param1', models.CharField(max_length=100)),
                ('param2', models.CharField(max_length=100)),
                ('param3', models.CharField(max_length=100)),
                ('param4', models.CharField(max_length=100)),
                ('param5', models.CharField(max_length=100)),
                ('param6', models.CharField(max_length=100)),
                ('param7', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
    ]
