# Generated by Django 5.2.4 on 2025-07-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achelper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='param5',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='param6',
            new_name='hemisphere',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='param3',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='param7',
            new_name='months',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='param1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='param2',
            new_name='shadow_size',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='param4',
            new_name='start_time',
        ),
    ]
