# Generated by Django 5.2.4 on 2025-07-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achelper', '0002_rename_param5_item_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
