# Generated by Django 5.2.4 on 2025-07-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achelper', '0003_alter_item_end_time_alter_item_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='always_available',
            field=models.BooleanField(default=False),
        ),
    ]
