# Generated by Django 5.2.4 on 2025-07-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achelper', '0004_item_always_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
